#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from contract_radar.agent_workflow import build_agent_brief  # noqa: E402
from contract_radar.core import ContractRadar  # noqa: E402


SAMPLE_PATH = ROOT / "samples" / "acme_services_agreement.md"
SPRINT_URL = "https://lolomix.github.io/contract-revenue-radar/sprint.html"
INTAKE_URL = "https://github.com/lolomix/contract-revenue-radar/issues/new/choose"
B2B_PACKAGE_URL = "https://github.com/lolomix/contract-revenue-radar/issues/new?template=b2b-business-package.yml"
PAID_REVIEW_START_URL = "https://github.com/lolomix/contract-revenue-radar/issues/new?template=paid-review-start.yml"
SERVICES_URL = "https://lolomix.github.io/contract-revenue-radar/services.html"
GENERIC_TRIGGERS = ("generic", "public-style", "public style", "sample first")


def parse_issue_form(body: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    current: str | None = None
    lines: list[str] = []

    def flush() -> None:
        nonlocal lines, current
        if current is not None:
            value = "\n".join(lines).strip()
            fields[current] = "" if value == "_No response_" else value
        lines = []

    for line in body.splitlines():
        if line.startswith("### "):
            flush()
            current = line[4:].strip()
        elif current is not None:
            lines.append(line)
    flush()
    return fields


def is_generic_request(text: str) -> bool:
    lowered = text.lower()
    return any(trigger in lowered for trigger in GENERIC_TRIGGERS)


def select_excerpt(fields: dict[str, str]) -> tuple[str, bool]:
    excerpt = fields.get("Redacted excerpt or public-style sample", "").strip()
    if len(excerpt) < 80 or is_generic_request(excerpt):
        return SAMPLE_PATH.read_text(encoding="utf-8"), True
    return excerpt, False


def clean_filename(contract_type: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9._-]+", "_", contract_type.strip().lower()).strip("_")
    return f"{name or 'sample'}_excerpt.md"


def truncate(text: str, limit: int = 320) -> str:
    compact = re.sub(r"\s+", " ", text).strip()
    if len(compact) <= limit:
        return compact
    return compact[: limit - 4].rstrip() + " ..."


def package_recommendation(risk_score: int, finding_count: int) -> tuple[str, str]:
    if risk_score >= 70 or finding_count >= 5:
        return (
            "B2B Business Package or Revenue Protection Sprint",
            "The sample shows enough revenue-risk density to justify a paid review if there are multiple recurring templates or SOW variants.",
        )
    if risk_score >= 40 or finding_count >= 3:
        return (
            "Audit + Negotiation Fallback Pack",
            "The sample shows several actionable risks. A paid pack is useful when the team needs fallback positions for counsel review.",
        )
    return (
        "Revenue Terms Audit",
        "The sample is lower density. Start with the smallest paid audit if the full document set has similar language.",
    )


def build_sample_comment(issue_body: str) -> str:
    fields = parse_issue_form(issue_body)
    excerpt, used_generic = select_excerpt(fields)
    organization = fields.get("Organization / team", "Requested sample").strip() or "Requested sample"
    contract_type = fields.get("Contract type", "Contract excerpt").strip() or "Contract excerpt"
    context = fields.get("Business context", "").strip()

    with tempfile.TemporaryDirectory() as tmpdir:
        sample_path = Path(tmpdir) / clean_filename(contract_type)
        sample_path.write_text(excerpt, encoding="utf-8")
        radar = ContractRadar(prefer_qdrant=False)
        report = radar.audit_paths([sample_path])

    brief = build_agent_brief(report)
    top_findings = report.findings[:3]
    recommended_package, recommendation_reason = package_recommendation(report.risk_score, len(report.findings))

    lines = [
        "## Automated 3-Finding Sample Audit",
        "",
        "This sample was generated by Contract Revenue Radar from the text in this public issue. It is business-risk review for sales, finance, delivery, and operations teams, not legal advice.",
        "",
        f"- Organization/team: **{organization}**",
        f"- Contract type: **{contract_type}**",
        f"- Backend: `{report.backend}`",
        f"- Revenue risk score: **{report.risk_score}/100**",
        f"- Sections searched: **{report.searched_sections}**",
    ]
    if context:
        lines.append(f"- Business context: {truncate(context, 180)}")
    if used_generic:
        lines.extend([
            "",
            "> I used the bundled public-style sample because the request did not include a long redacted excerpt, or it asked for a generic sample first.",
        ])

    if not top_findings:
        lines.extend([
            "",
            "No high-signal revenue-risk findings were detected in the provided excerpt. If this is a real evaluation, add a longer redacted sample with payment, acceptance, scope, renewal, credit, security, or IP language.",
        ])
    else:
        lines.extend(["", "### Top Findings"])
        for index, finding in enumerate(top_findings, 1):
            matched = ", ".join(finding.matched_terms) if finding.matched_terms else "semantic match"
            lines.extend([
                "",
                f"#### {index}. {finding.label} - severity {finding.severity}/5",
                f"- Source: `{finding.source}` / {finding.heading}",
                f"- Matched terms: {matched}",
                f"- Why it matters: {finding.why}",
                f"- Recommended move: {finding.action}",
                "",
                f"> {truncate(finding.excerpt)}",
            ])

    lines.extend([
        "",
        "### Package Recommendation",
        "",
        f"Recommended next scope: **{recommended_package}**.",
        "",
        recommendation_reason,
        "",
        "Close-ready approval language for a paid review can be routed privately, through procurement, or through a platform-approved order path. Keep billing, tax, payment, and private document details out of this public issue.",
        "",
        "",
        "### Priority Questions",
    ])
    for question in brief.priority_questions[:5]:
        lines.append(f"- {question}")

    lines.extend([
        "",
        "### Fallback Positions",
    ])
    for fallback in brief.fallback_positions[:5]:
        lines.append(f"- {fallback}")

    lines.extend([
        "",
        "### Next Step",
        "",
        f"Compare paid package scopes: {SERVICES_URL}",
        "",
        f"If this sample is useful and you have up to 15 recurring templates or excerpts, request the $3,500 B2B Business Package: {B2B_PACKAGE_URL}",
        "",
        f"If you are ready to route payment/procurement for any paid review, open a public-safe Start Paid Review request: {PAID_REVIEW_START_URL}",
        "",
        f"If you have 15-25 recurring SOWs/MSAs/order forms/templates, review the fixed-scope $5,000 Revenue Protection Sprint: {SPRINT_URL}",
        "",
        f"To request a broader sprint without posting private documents, use the intake page and describe the template count and deal motion only: {INTAKE_URL}",
        "",
        "_Do not post confidential contracts, personal data, credentials, or private client information in public GitHub issues._",
    ])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    if len(args) != 1:
        print("Usage: issue_sample_audit.py GITHUB_EVENT_JSON", file=sys.stderr)
        return 2
    event = json.loads(Path(args[0]).read_text(encoding="utf-8"))
    body = event.get("issue", {}).get("body", "")
    sys.stdout.write(build_sample_comment(body))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
